### ISSUE TITLE
Calling a function defined in a .m file

### ISSUE THREAD

**Issue by alexpghayes** [muschellij2/matlabr#1]
Having some trouble figuring out how to call a user defined function. I have a function `[output] = my_function(input)` defined in `my_function.m` and would like to call `my_function` from R. Can you point me in the right direction?

**Comment by muschellij2** [comment]
Can you be a little bit more specific?  In MATLAB, you need to add the folder that has the `.m` file needs to be added to the PATH.

To use this functionality, you need to install the development version:

```r
devtools::install_github("muschellij2/matlabr")
```

I have added arguments to `run_matlab_code` so that you can do:
```
run_matlab_code("[output] = my_function(input)", paths_to_add = "/path/to/function")
```

Where `"/path/to/function"` is the path to the `my_function.m`.  Otherwise set the PATH argument in MATLAB.  You can use

```
run_matlab_code("[output] = my_function(input)", paths_to_add = "/path/to/function")
```

**Comment by alexpghayes** [comment]
This was what I needed, thanks.
